services:
  postgres:
    image: postgres:14@sha256:fbd63b8e1eb2b318d342e8ad279891f622aa5ff69bd95e5683cc915301218bcf
    environment:
      POSTGRES_DB: nextpress
      POSTGRES_USER: nextpress
      POSTGRES_PASSWORD: nextpress_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgweb:
    image: sosedoff/pgweb@sha256:8f1ed22e10c9da0912169b98b62ddc54930dc39a5ae07b0f1354d2a93d44c6ed
    environment:
      DATABASE_URL: postgres://nextpress:nextpress_password@postgres:5432/nextpress?sslmode=disable
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  mailpit:
    image: axllent/mailpit@sha256:b1f1be18af530d939a11ee8820b379e0c88eeec204d904bfad68862adced3a5a
    container_name: mailpit
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

volumes:
  postgres_data:

