services:
  postgres:
    image: postgres:14@sha256:bbb8851608e3ff4901156bf6a4bf90735a9d44ae014c03811bfdb2f9c354b18b
    environment:
      POSTGRES_DB: nextpress
      POSTGRES_USER: nextpress
      POSTGRES_PASSWORD: nextpress_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgweb:
    image: sosedoff/pgweb@sha256:a5256d416e2e8b92d69a4459058e3eca33a9f075d8325491644411d0bc3bd70b
    environment:
      DATABASE_URL: postgres://nextpress:nextpress_password@postgres:5432/nextpress?sslmode=disable
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  mailpit:
    image: axllent/mailpit@sha256:757f22b56c1da03570afdb3d259effe5091018008a81bbedc8158cee7e16fdbc
    container_name: mailpit
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

volumes:
  postgres_data:

